[build]
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22.16.0"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-react-static"